image: node:latest
  
stages:
  - build
  - tests
  - deploiement

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  
build_dev:
  stage: build
  script: 
    - ssh -T git@git.nextoo.fr
    - ssh -T git@git.nextoo.fr "git submodule sync --recursive && git submodule update --init --recursive"
    - npm install
    - npm run build-dev
  artifacts:
    paths:
      - dist/
    expire_in: 1h
  only:
    - dev

build_master:
  stage: build
  script: 
    - npm install
    - npm run build-prod
  artifacts:
    paths:
      - dist/
    expire_in: 1h
  only:
    - master
    
tests:
  stage: tests
  script: 
  - echo 'test'
  only:
  - branches
  
deploiement_dev:
  stage: deploiement
  script: 
    - echo 'Deploiement sur dev'
  only:
    - dev

deploiement_master:
  stage: deploiement
  script: 
    - echo 'Deploiement sur dev'
  only:
    - master