image: node:latest
  
stages:
  - build
  - tests
  - deploiement

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - git submodule sync --recursive
  - git submodule update --init --recursive

  
build_dev:
  stage: build
  script: 
    - npm install
    - npm run build-dev
  artifacts:
    paths:
      - dist/
    expire_in: 1h
  only:
    - dev

build_master:
  stage: build
  script: 
    - npm install
    - npm run build-prod
  artifacts:
    paths:
      - dist/
    expire_in: 1h
  only:
    - master
    
tests:
  stage: tests
  script: 
  - echo 'test'
  only:
  - branches
  
deploiement_dev:
  stage: deploiement
  script: 
    - echo 'Deploiement sur dev'
  only:
    - dev

deploiement_master:
  stage: deploiement
  script: 
    - echo 'Deploiement sur dev'
  only:
    - master